env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - '@nuxt/eslint-config'
  - prettier
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  project: ./tsconfig.json
