version: '3'
services:
  xmmx-ccxt-server:
    hostname: xmmx-ccxt-server
    container_name: xmmx-ccxt-server
    build:
      context: lib/ccxt-server
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./apis.json:/usr/src/app/apis.json
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - CCXT_SERVER_APIS=/usr/src/app/apis.json

  xmmx-nuxt-client:
    hostname: xmmx-nuxt-client
    container_name: xmmx-nuxt-client
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    restart: always
    ports:
      - '3000:3000'
      - '24678:24678'
    environment:
      # CSRなのでブラウザ（ホストマシンからみた時のccxt-serverのURLになる）
      - CCXT_SERVER_URL=http://0.0.0.0:3001
    entrypoint: sh -c 'yarn dev'
    depends_on:
      - xmmx-ccxt-server
